[package]
name = "nes"
version = "1.0.12"
authors = ["mantou132"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tetanes = { path = "../../deps/tetanes", default_features = false }
nesbox_utils = { path = "utils" }
