[workspace]
members = [
  "packages/nes",
  "packages/server",
  "packages/tauriapp"
]

exclude = ["deps/tetanes"]

[profile.release.package.nes]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
debug = true