[package]
name = "server"
version = "0.1.0"
edition = "2021"
default-run = "server"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres", "chrono", "r2d2", "serde_json"] }
dotenv = "0.15.0"

actix-web = "4"
actix-web-lab = "0.16.1"
actix-cors = "0.6"

juniper = "0.15"

env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1.0.123"
chrono='0.4.19'
jsonwebtoken = "8.1.0"

data-encoding = "2.3.2"
ring = "0.16.20"